---
name: RPSL-Parser
version: 0.38
author:
  - 'Luis Motta Campos, E<lt>lmc@cpan.orgE<gt>'
abstract: Router Policy Specification Language (RFC2622) Parser
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  RPSL::Parser:
    file: lib/RPSL/Parser.pm
    version: 0.38
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
